name: Dev build and publish jar to sonatype repo

on:
  push:
    branches-ignore:
      - master
      - version-*

jobs:
  sonatype-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Sonatype'
    secrets:
      SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      SONATYPE_GPG_ARMORED_KEY: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      SONATYPE_SIGNING_PASSWORD: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}